if(NOT DEFINED WEB_DIST)
    message(FATAL_ERROR "WEB_DIST is required")
endif()
if(NOT DEFINED OUT_CPP)
    message(FATAL_ERROR "OUT_CPP is required")
endif()
if(NOT DEFINED OUT_HPP)
    message(FATAL_ERROR "OUT_HPP is required")
endif()

file(GLOB_RECURSE asset_files "${WEB_DIST}/*")
list(SORT asset_files)

file(WRITE "${OUT_HPP}" "#pragma once\n\n")
file(APPEND "${OUT_HPP}" "#include <cstddef>\n")
file(APPEND "${OUT_HPP}" "#include <string_view>\n\n")
file(APPEND "${OUT_HPP}" "namespace echoir {\n\n")
file(APPEND "${OUT_HPP}" "struct WebAsset {\n")
file(APPEND "${OUT_HPP}" "    const char* path;\n")
file(APPEND "${OUT_HPP}" "    const char* mimeType;\n")
file(APPEND "${OUT_HPP}" "    const unsigned char* data;\n")
file(APPEND "${OUT_HPP}" "    std::size_t size;\n")
file(APPEND "${OUT_HPP}" "};\n\n")
file(APPEND "${OUT_HPP}" "const WebAsset* embeddedWebAssets(std::size_t& count);\n")
file(APPEND "${OUT_HPP}" "const WebAsset* findEmbeddedWebAsset(std::string_view path);\n\n")
file(APPEND "${OUT_HPP}" "}  // namespace echoir\n")

file(WRITE "${OUT_CPP}" "#include \"echoir_web_assets.hpp\"\n\n")
file(APPEND "${OUT_CPP}" "#include <algorithm>\n")
file(APPEND "${OUT_CPP}" "#include <string_view>\n\n")
file(APPEND "${OUT_CPP}" "namespace echoir {\nnamespace {\n\n")

set(entries "")
set(index 0)
foreach(asset IN LISTS asset_files)
    if(IS_DIRECTORY "${asset}")
        continue()
    endif()

    file(RELATIVE_PATH rel "${WEB_DIST}" "${asset}")
    string(REPLACE "\\" "/" rel "${rel}")
    set(asset_path "/${rel}")
    get_filename_component(ext "${asset}" EXT)
    string(TOLOWER "${ext}" ext)

    set(mime "application/octet-stream")
    if(ext STREQUAL ".html")
        set(mime "text/html; charset=utf-8")
    elseif(ext STREQUAL ".css")
        set(mime "text/css; charset=utf-8")
    elseif(ext STREQUAL ".js")
        set(mime "text/javascript; charset=utf-8")
    elseif(ext STREQUAL ".json")
        set(mime "application/json; charset=utf-8")
    elseif(ext STREQUAL ".svg")
        set(mime "image/svg+xml")
    elseif(ext STREQUAL ".png")
        set(mime "image/png")
    elseif(ext STREQUAL ".ico")
        set(mime "image/x-icon")
    elseif(ext STREQUAL ".txt")
        set(mime "text/plain; charset=utf-8")
    elseif(ext STREQUAL ".woff")
        set(mime "font/woff")
    elseif(ext STREQUAL ".woff2")
        set(mime "font/woff2")
    endif()

    file(READ "${asset}" hex HEX)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," bytes "${hex}")
    file(APPEND "${OUT_CPP}" "const unsigned char asset_${index}[] = {${bytes}};\n")
    string(APPEND entries "    {\"${asset_path}\", \"${mime}\", asset_${index}, sizeof(asset_${index})},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(APPEND "${OUT_CPP}" "\nconst WebAsset kAssets[] = {\n${entries}};\n\n")
file(APPEND "${OUT_CPP}" "}  // namespace\n\n")
file(APPEND "${OUT_CPP}" "const WebAsset* embeddedWebAssets(std::size_t& count) {\n")
file(APPEND "${OUT_CPP}" "    count = sizeof(kAssets) / sizeof(kAssets[0]);\n")
file(APPEND "${OUT_CPP}" "    return kAssets;\n")
file(APPEND "${OUT_CPP}" "}\n\n")
file(APPEND "${OUT_CPP}" "const WebAsset* findEmbeddedWebAsset(std::string_view path) {\n")
file(APPEND "${OUT_CPP}" "    std::size_t count = 0;\n")
file(APPEND "${OUT_CPP}" "    const auto* assets = embeddedWebAssets(count);\n")
file(APPEND "${OUT_CPP}" "    const auto it = std::find_if(assets, assets + count, [path](const WebAsset& asset) {\n")
file(APPEND "${OUT_CPP}" "        return path == asset.path;\n")
file(APPEND "${OUT_CPP}" "    });\n")
file(APPEND "${OUT_CPP}" "    return it == assets + count ? nullptr : it;\n")
file(APPEND "${OUT_CPP}" "}\n\n")
file(APPEND "${OUT_CPP}" "}  // namespace echoir\n")
